apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-twfs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-twfs
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-twfs
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-twfs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-twfs
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/happy-path-bwnk-tenant/appstudio/dc-metro-map-twfs@sha256:8d5fb955cab4fb6cffe0e51accbe04a9da5e358b19654c8f545b0456e73a8ef3
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
